### ISSUE TITLE
modest proposal

### ISSUE THREAD

**Issue by Spider4Tech** [oligamiq/yarrow-rs#1]
Hi, i've seen you're pretty good in prng stuff and in rust, are you interested in working to improve my project ?

ty 

Horizon-team

**Comment by oligamiq** [comment]
Sorry.
First, I'm not good at English.
Second, I'm not familiar with cryptography.
Third, I'm student so busy.

**Comment by Spider4Tech** [comment]
ok no pbm, we are student too and we learned cryptography by working on it, if you change your mind : cameleon2994 
( discord)
